#!/usr/bin/env python3
"""Merge JTBD records from all assemblies into a single JSONL file."""

import json

# Assembly 2 records (Web Console)
assembly2_records = [
    {"doc":"create-combined.adoc","section":"Working with OpenShift Pipelines in the Developer perspective","job_statement":"When I need to create CI/CD pipelines for my application, I want to access pipeline creation options from the Developer perspective, so I can build automated delivery workflows integrated with my development process.","job_type":"core","persona":"Application developer","job_map_stage":"Configure","granularity":"main_job","parent_job":None,"prerequisites":[],"related_jobs":["Deploy applications using pipelines","Monitor pipeline execution"],"desired_outcomes":["Minimize time to create a working pipeline","Reduce complexity of pipeline configuration","Ensure pipelines integrate with application lifecycle"],"evidence":"create-combined.adoc -> Working with OpenShift Pipelines in the Developer perspective, lines 1503-1512","notes":"Main job covering pipeline creation in Developer perspective. Two primary approaches: Pipeline builder and From Git option."},
    {"doc":"create-combined.adoc","section":"Constructing pipelines using the Pipeline builder","job_statement":"As an application developer, when I need to create a customized pipeline, I want to use the Pipeline builder with visual configuration, so I can construct pipelines using reusable tasks without writing YAML manually.","job_type":"core","persona":"Application developer","job_map_stage":"Configure","granularity":"user_story","parent_job":"Create CI/CD pipelines for my application","prerequisites":[],"related_jobs":["Search and add tasks from Tekton Hub","Configure pipeline resources and parameters"],"desired_outcomes":["Minimize time to configure pipeline tasks","Reduce errors from manual YAML editing","Ensure access to reusable pipeline tasks from the cluster"],"evidence":"create-combined.adoc -> Constructing pipelines using the Pipeline builder, lines 1522-1606","notes":"UI-based approach using Pipeline builder. Supports both visual builder and YAML view. Requires Tekton Hub for full task catalog access."},
    {"doc":"create-combined.adoc","section":"Constructing pipelines using the Pipeline builder","job_statement":"As a cluster administrator, when I want to enable developers to access curated tasks, I want to install and deploy a local Tekton Hub instance, so developers can search, install, and upgrade tasks directly from the console.","job_type":"related","persona":"Cluster administrator","job_map_stage":"Configure","granularity":"user_story","parent_job":"Create CI/CD pipelines for my application","prerequisites":["Install OpenShift Pipelines Operator"],"related_jobs":["Deploy Tekton Hub instance","Link Tekton Hub to OpenShift cluster"],"desired_outcomes":["Ensure developers have access to curated task catalog","Minimize dependency on public Tekton Hub","Reduce likelihood of using untrusted tasks"],"evidence":"create-combined.adoc -> Constructing pipelines using the Pipeline builder, lines 1535-1539","notes":"Related job for administrators to enable developer self-service. Without local Tekton Hub, developers only access namespace tasks and public hub tasks."},
    {"doc":"create-combined.adoc","section":"Creating OpenShift Pipelines along with applications","job_statement":"As an application developer, when I am deploying a new application from Git, I want to create pipelines using templates during application import, so I can establish CI/CD automation from the start without separate pipeline creation steps.","job_type":"core","persona":"Application developer","job_map_stage":"Configure","granularity":"user_story","parent_job":"Create CI/CD pipelines for my application","prerequisites":[],"related_jobs":["Import codebase from Git","View pipelines in Topology view"],"desired_outcomes":["Minimize time between code import and automated builds","Ensure pipelines are automatically linked to application","Reduce steps required to enable CI/CD"],"evidence":"create-combined.adoc -> Creating OpenShift Pipelines along with applications, lines 1615-1627","notes":"From Git approach enables pipeline creation during application import. Default webhooks are added automatically. Tekton Hub integration shows available tasks."},
    {"doc":"create-combined.adoc","section":"Adding a GitHub repository containing pipelines","job_statement":"As an application developer, when I have pipelines defined in my GitHub repository, I want to add the repository to the cluster with webhook configuration, so pipelines run automatically on Git events like push and pull requests.","job_type":"core","persona":"Application developer","job_map_stage":"Configure","granularity":"user_story","parent_job":"Create CI/CD pipelines for my application","prerequisites":["Cluster administrator has configured GitHub applications","Have GitHub repository with .tekton directory"],"related_jobs":["Configure Pipelines as Code","Set up GitHub webhooks"],"desired_outcomes":["Ensure pipelines trigger automatically on Git events","Minimize manual pipeline execution","Reduce time to establish event-driven CI/CD"],"evidence":"create-combined.adoc -> Adding a GitHub repository containing pipelines, lines 1637-1694","notes":"Supports both public and private GitHub repositories. Requires GitHub App or webhook setup with personal access token. Prerequisite: admin must configure GitHub apps first."},
    {"doc":"create-combined.adoc","section":"Interacting with pipelines using the Developer perspective","job_statement":"When I have created pipelines, I want to view pipeline details and execution status in a visual interface, so I can understand pipeline structure, monitor runs, and troubleshoot failures efficiently.","job_type":"core","persona":"Application developer","job_map_stage":"Monitor","granularity":"main_job","parent_job":None,"prerequisites":["Create a pipeline"],"related_jobs":["Start pipeline runs","Debug failed pipeline runs","View pipeline metrics"],"desired_outcomes":["Minimize time to identify failed tasks","Reduce effort to understand pipeline structure","Ensure quick access to logs and error details"],"evidence":"create-combined.adoc -> Interacting with pipelines using the Developer perspective, lines 1704-1766","notes":"Main job covering pipeline monitoring and interaction. Developer perspective provides visual representation of serial tasks, parallel tasks, finally tasks, and when expressions."},
    {"doc":"create-combined.adoc","section":"Starting pipelines from Pipelines view","job_statement":"When I have created a pipeline, I want to start it with configured resources and credentials, so the included tasks execute in the defined sequence to build and deploy my application.","job_type":"core","persona":"Application developer","job_map_stage":"Execute","granularity":"main_job","parent_job":None,"prerequisites":["Create a pipeline","Define pipeline resources"],"related_jobs":["Configure Git resources","Configure image resources","Add authentication secrets"],"desired_outcomes":["Minimize time to execute pipeline run","Reduce errors from missing resources or credentials","Ensure pipeline tasks execute successfully"],"evidence":"create-combined.adoc -> Starting pipelines from Pipelines view, lines 1775-1839","notes":"Main job covering pipeline execution. Can start from Pipelines view, Pipeline Details page, or Topology view. Supports adding secrets for private Git servers and image registries."},
    {"doc":"create-combined.adoc","section":"Editing pipelines","job_statement":"When I need to modify an existing pipeline, I want to edit pipeline configuration through the web console, so I can add tasks, change parameters, or update resources without recreating the entire pipeline.","job_type":"core","persona":"Application developer","job_map_stage":"Modify","granularity":"main_job","parent_job":None,"prerequisites":["Have an existing pipeline"],"related_jobs":["Add pipeline tasks","Configure task parameters","Remove pipeline tasks"],"desired_outcomes":["Minimize time to update pipeline configuration","Reduce risk of breaking working pipelines","Ensure changes are applied without pipeline recreation"],"evidence":"create-combined.adoc -> Editing pipelines, lines 1897-1912","notes":"Main job covering pipeline modification. Uses Pipeline builder page for visual editing. Can add/remove tasks, modify parameters, and update resources."},
    {"doc":"create-combined.adoc","section":"Creating pipeline templates in the Administrator perspective","job_statement":"As a cluster administrator, when I want to provide reusable pipeline patterns, I want to create pipeline templates in the openshift namespace, so developers can reuse standardized pipelines across projects.","job_type":"core","persona":"Cluster administrator","job_map_stage":"Configure","granularity":"main_job","parent_job":None,"prerequisites":["Have cluster administrator permissions","Install OpenShift Pipelines Operator"],"related_jobs":["Define runtime labels for templates","Define pipeline type labels"],"desired_outcomes":["Minimize developer effort to create common pipelines","Ensure consistent pipeline patterns across teams","Reduce duplication of pipeline definitions"],"evidence":"create-combined.adoc -> Creating pipeline templates in the Administrator perspective, lines 1945-1981","notes":"Administrator-specific job for creating reusable templates. Templates must be created in openshift namespace with runtime and type labels."},
    {"doc":"create-combined.adoc","section":"Pipeline execution statistics in the web console","job_statement":"When I need to analyze pipeline performance across my organization, I want to view consolidated execution statistics, so I can identify trends, optimize workflows, and report on CI/CD effectiveness.","job_type":"core","persona":"Platform administrator","job_map_stage":"Analyze","granularity":"main_job","parent_job":None,"prerequisites":["Install Tekton Results","Enable OpenShift Pipelines console plugin"],"related_jobs":["Monitor pipeline success ratios","Track pipeline run durations","View pipeline run trends"],"desired_outcomes":["Minimize time to identify performance trends","Ensure visibility into pipeline success rates","Reduce effort to generate pipeline reports"],"evidence":"create-combined.adoc -> Pipeline execution statistics in the web console, lines 1990-2002","notes":"Requires Tekton Results installation and console plugin enablement. Provides statistics for all pipelines together and individual pipelines."}
]

# Assembly 3 records (Resolvers) - placeholder, will be collected from agent output
assembly3_records = []

# Assembly 4 records (Manual Approval)
assembly4_records = [
    {"doc":"create-combined.adoc","section":"Enabling the manual approval gate controller","job_statement":"When I need to implement approval gates in my CI/CD pipelines, I want to enable the manual approval gate controller, so I can ensure critical deployments require human authorization before proceeding.","job_type":"core","persona":"Platform administrator","job_map_stage":"Configure","granularity":"user_story","parent_job":"Control pipeline execution with manual approval gates","prerequisites":["Install OpenShift Pipelines Operator","Have administrator permissions for openshift-pipelines namespace","Have cluster access via oc CLI"],"related_jobs":["Specify approval tasks in pipelines","Configure pipeline approvers"],"desired_outcomes":["Minimize time to enable approval capability","Ensure approval controller is ready before pipeline execution","Reduce likelihood of deploying without required authorization"],"evidence":"create-combined.adoc -> Enabling the manual approval gate controller, lines 5787-5834","notes":"Technology Preview feature. This is a prerequisite configuration step before approval tasks can be used in pipelines."},
    {"doc":"create-combined.adoc","section":"Specifying a manual approval task","job_statement":"When I need to control when pipelines proceed to critical stages, I want to configure approval tasks with specific approvers and thresholds, so I can ensure the right stakeholders authorize production deployments.","job_type":"core","persona":"DevOps engineer","job_map_stage":"Configure","granularity":"user_story","parent_job":"Control pipeline execution with manual approval gates","prerequisites":["Enable the manual approval gate controller","Have a pipeline YAML specification","Create groups and add required users for group approval"],"related_jobs":["Define deployment pipelines","Configure build and test tasks","Set up production environments"],"desired_outcomes":["Minimize configuration errors when defining approval gates","Ensure correct number of approvals required","Reduce likelihood of unauthorized deployments","Ensure approval timeout prevents indefinite pipeline blocking"],"evidence":"create-combined.adoc -> Specifying a manual approval task, lines 5842-6076","notes":"Supports multiple approval patterns: multi-user approval (requires N approvals from individual users), group-based approval (requires approvals from group members), and mixed user/group approval. Default timeout is 1 hour."},
    {"doc":"create-combined.adoc","section":"Approving a manual approval task by using the web console","job_statement":"When a pipeline reaches an approval gate that lists me as an approver, I want to approve or reject the task via the web console, so I can authorize or block critical deployments without using CLI tools.","job_type":"core","persona":"Pipeline approver","job_map_stage":"Operate","granularity":"user_story","parent_job":"Authorize or reject pipeline execution at approval gates","prerequisites":["Enable OpenShift Pipelines console plugin","Be listed as an approver in the approval task","Have a pipeline run waiting at an approval gate"],"related_jobs":["Monitor pipeline execution","Review deployment changes","View pipeline run details"],"desired_outcomes":["Minimize time to locate pending approvals","Reduce likelihood of missing approval notifications","Ensure approval decisions are recorded with reason","Minimize errors when approving or rejecting"],"evidence":"create-combined.adoc -> Approving a manual approval task by using the web console, lines 6106-6131","notes":"Web console provides notifications when approval is required. Multiple access points: notification link, Pipelines Approvals tab (Administrator and Developer perspectives), PipelineRun details window."},
    {"doc":"create-combined.adoc","section":"Approving a manual approval task by using the command line","job_statement":"When a pipeline reaches an approval gate that lists me as an approver, I want to approve or reject the task via the opc CLI, so I can authorize or block critical deployments from my terminal workflow.","job_type":"core","persona":"Pipeline approver","job_map_stage":"Operate","granularity":"user_story","parent_job":"Authorize or reject pipeline execution at approval gates","prerequisites":["Download and install opc CLI utility","Be listed as an approver in the approval task","Have cluster access via oc CLI","Have a pipeline run waiting at an approval gate"],"related_jobs":["Monitor pipeline execution via CLI","View pipeline run status","Review deployment changes"],"desired_outcomes":["Minimize time to view pending approvals","Reduce likelihood of approving wrong task","Ensure approval decisions include optional reason message","Minimize errors in CLI command syntax"],"evidence":"create-combined.adoc -> Approving a manual approval task by using the command line, lines 6145-6209","notes":"opc CLI is available in same package as tkn CLI. Supports list, describe, approve, and reject operations. Optional -m parameter for adding approval/rejection message."},
    {"doc":"create-combined.adoc","section":"Behavior of ApprovalTask with groups and users","job_statement":"When I configure approval tasks with groups and users, I want to understand how the controller tracks individual and group-level approvals, so I can design approval policies that require sign-off from specific roles and teams.","job_type":"core","persona":"DevOps engineer","job_map_stage":"Configure","granularity":"user_story","parent_job":"Control pipeline execution with manual approval gates","prerequisites":["Enable the manual approval gate controller","Understand approval task configuration","Create required groups with members"],"related_jobs":["Specify approval tasks in pipelines","Design deployment governance policies","Configure role-based access control"],"desired_outcomes":["Minimize confusion about group approval behavior","Ensure approval policies match organizational requirements","Reduce likelihood of misconfiguring mixed user/group approvals","Understand how individual group member approvals are tracked"],"evidence":"create-combined.adoc -> Behavior of ApprovalTask with groups and users, lines 6218-6286","notes":"Controller automatically tracks individual approvals from group members and updates group approval state. Supports complex policies combining individual users and groups."}
]

# Assembly 5 records (Entitlements)
assembly5_records = [
    {"doc":"create-combined.adoc","section":"Using Red Hat entitlements in pipelines","job_statement":"When building container images in pipelines that require RHEL packages, I want to use Red Hat entitlements, so I can access RHEL repositories during the build process.","job_type":"core","persona":"Pipeline developer","job_map_stage":"Configure","granularity":"main_job","parent_job":None,"prerequisites":["Enable the Insights Operator feature on the OpenShift cluster","Configure importing of Red Hat entitlements into the Insights Operator from Simple Content Access (SCA)","Log in to the OpenShift cluster using the oc CLI"],"related_jobs":["Build container images using Buildah task","Configure pipeline workspaces","Manage secrets across namespaces"],"desired_outcomes":["Minimize time required to configure entitlement access","Reduce likelihood of build failures due to missing RHEL packages","Ensure entitlements are securely managed across pipeline namespaces","Avoid manual secret management overhead"],"evidence":"create-combined.adoc -> Using Red Hat entitlements in pipelines (abstract and overview), lines 6358-6368","notes":"This main job has two distinct user stories for different implementation approaches: manual secret copying (simpler, for few namespaces) vs CSI driver (automated, for many namespaces)."},
    {"doc":"create-combined.adoc","section":"Using Red Hat entitlements by manually copying the etc-pki-entitlement secret","job_statement":"When I have a limited number of pipeline namespaces and need RHEL entitlements for builds, I want to manually copy the etc-pki-entitlement secret to each namespace, so I can provide entitlements without additional operator configuration.","job_type":"core","persona":"Pipeline developer","job_map_stage":"Configure","granularity":"user_story","parent_job":"Use Red Hat entitlements in pipelines","prerequisites":["Install the jq package on your system","Enable the Insights Operator feature","Configure importing of Red Hat entitlements into the Insights Operator","Verify that the etc-pki-entitlement secret exists in the openshift-config-managed namespace"],"related_jobs":["Configure Buildah task to use rhel-entitlement workspace","Define workspaces in pipeline runs","Manage pipeline secrets"],"desired_outcomes":["Minimize complexity of entitlement setup for simple use cases","Reduce dependencies on additional operators","Ensure entitlement secret is correctly formatted in target namespace","Complete entitlement setup in under 5 minutes for small deployments"],"evidence":"create-combined.adoc -> Using Red Hat entitlements by manually copying the etc-pki-entitlement secret, lines 6412-6493","notes":"Recommended when there are a limited number of pipeline namespaces. Requires jq for JSON manipulation."},
    {"doc":"create-combined.adoc","section":"Using Red Hat entitlements by sharing the secret using the Shared Resources CSI driver operator","job_statement":"When I need RHEL entitlements across many pipeline namespaces, I want to automatically share the etc-pki-entitlement secret using the Shared Resources CSI Driver, so I can avoid manual secret copying and ensure consistent entitlement access.","job_type":"core","persona":"Platform engineer","job_map_stage":"Configure","granularity":"user_story","parent_job":"Use Red Hat entitlements in pipelines","prerequisites":["Log in to the OpenShift cluster as a user with cluster administrator permissions","Enable the Shared Resources CSI Driver operator on the cluster","Enable the Insights Operator feature","Configure importing of Red Hat entitlements into the Insights Operator","Verify that the etc-pki-entitlement secret exists in the openshift-config-managed namespace"],"related_jobs":["Configure RBAC for shared resources","Manage service account permissions for pipelines","Configure Buildah task to use rhel-entitlement workspace"],"desired_outcomes":["Minimize manual secret management overhead across multiple namespaces","Reduce likelihood of entitlement configuration drift between namespaces","Ensure automatic entitlement availability for new pipeline namespaces","Centralize entitlement secret management"],"evidence":"create-combined.adoc -> Using Red Hat entitlements by sharing the secret using the Shared Resources CSI driver operator, lines 6501-6628","notes":"Requires cluster admin permissions. Recommended when using the Shared Resources CSI Driver. Creates SharedSecret CR with RBAC."}
]

# Write all records to JSONL
output_file = "/Users/roparmar/git/openshift-docs/analysis/openshift-pipelines/create/create-jtbd-partial.jsonl"

# Read existing assembly 1 records
with open("/Users/roparmar/git/openshift-docs/analysis/openshift-pipelines/create/create-jtbd.jsonl", 'r') as f:
    assembly1_records = [json.loads(line) for line in f]

# Combine all records
all_records = assembly1_records + assembly2_records + assembly4_records + assembly5_records

# Write combined
with open(output_file, 'w') as f:
    for record in all_records:
        f.write(json.dumps(record) + '\n')

print(f"Wrote {len(all_records)} records to {output_file}")
print(f"  Assembly 1: {len(assembly1_records)} records")
print(f"  Assembly 2: {len(assembly2_records)} records")
print(f"  Assembly 3: 0 records (to be added from agent output)")
print(f"  Assembly 4: {len(assembly4_records)} records")
print(f"  Assembly 5: {len(assembly5_records)} records")
